apiVersion: apps/v1

kind: Deployment

metadata:
  name: demo-app-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

    spec:
      containers:
      - name: demo-app

        image: prabhu4511/demo-app:latest
         imagePullPolicy:Always

        ports:
        - containerPort: 3000